package com.mchub.enums;

public enum AuditAction {

    // Auth
    AUTH_LOGIN,
    AUTH_LOGIN_FAILED,
    AUTH_LOGOUT,
    AUTH_REGISTER,
    AUTH_CHANGE_PASSWORD,
    AUTH_RESET_PASSWORD,

    // Booking
    BOOKING_CREATE,
    BOOKING_ACCEPT,
    BOOKING_REJECT,
    BOOKING_CANCEL,
    BOOKING_COMPLETE,

    // Payment
    PAYMENT_INITIATE,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUND,

    // Profile
    PROFILE_UPDATE,
    PROFILE_AVATAR_UPDATE,
    MC_PROFILE_UPDATE,

    // Admin
    ADMIN_BAN_USER,
    ADMIN_UNBAN_USER,
    ADMIN_RESOLVE_REPORT,
    ADMIN_VERIFY_CERTIFICATE,
    ADMIN_CREATE_COUPON,
    ADMIN_DELETE_USER,
    ADMIN_UPDATE_USER_STATUS,
    ADMIN_CHANGE_PASSWORD,
    ADMIN_CREATE_USER,
    ADMIN_LOGIN_OTP_VERIFY,
    ADMIN_PURGE_LOGS,
    ADMIN_SEND_RESET_EMAIL,
    ADMIN_NOTIFY_EMAIL,
    ADMIN_MIGRATE_DB,

    // System
    SYSTEM_AUTO_ACTION
}
