package com.mchub.enums;

public enum EventType {
    WEDDING,
    ENGAGEMENT,
    GALA_DINNER,
    CORPORATE_CONFERENCE,
    SEMINAR_WORKSHOP,
    PRODUCT_LAUNCH,
    TEAM_BUILDING,
    YEAR_END_PARTY,
    GRAND_OPENING,
    INAUGURATION,
    CONCERT,
    FESTIVAL,
    EXHIBITION,
    BIRTHDAY_PARTY,
    GRADUATION,
    FASHION_SHOW,
    COMPETITION,
    CHARITY_EVENT,
    DIPLOMATIC_EVENT,
    OTHER
}
